title: PROi Scribbles
description: The PROi (PvM Run on Iron) scribbles is one players journey documenting how to avoid mid game plateau fatigue and get to high level PvM quickly.
theme: just-the-docs
color_scheme: light

aux_links:
  Template Repository: todo

just_the_docs:
  include_head: head_custom.html

plugins:
  - jekyll-redirect-from
